apiVersion: apps/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ContainerDeploymentUnit # Should generate a uniq name
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: Nodecellar # Should generate a uniq name
        env:
          LOG_LEVEL: "DEBUG"
          MONGO_HOST: {DEPENDENCY_IP_ADDRESS}
          MONGO_PORT: {DEPENDENCY_PORT}
          NODECELLAR_PORT: 3000
        image: afraisse/nodecellar:exp
        resources:
          requests:
            memory: 1024M
            cpu: 1.0
          limits:
            memory: 1024M
            cpu: 1.0
        command: ["/bin/bash", "-c", "cd /nodecellar && nodejs server.js" ]
        ports:
        - containerPort: 3000
      - name: Nodecellar_2
        env:
          LOG_LEVEL: "DEBUG"
          MONGO_HOST: {DEPENDENCY_2_IP_ADDRESS}
          MONGO_PORT: {DEPENDENCY_2_PORT}
          NODECELLAR_PORT: 4000
        image: afraisse/nodecellar:exp
        resources:
          requests:
            memory: 1024M
            cpu: 1.0
          limits:
            memory: 1024M
            cpu: 1.0
        command: ["/bin/bash", "-c", "cd /nodecellar && nodejs server.js" ]
        ports:
        - containerPort: 4000