apiVersion: extension/v1beta # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: Mongo # Should generate a uniq name
  labels:
    anti_affinity_label: Mongo

deployment:
  spec:
    replicas: 1
    template:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: anti_affinity_label
                    operator: In
                    values:
                    - Mongo_2
                topologyKey: kubernetes.io/hostname
        containers:
          - name: Mongo
            image: mongo:latest
            resources:
              requests:
                memory: 512M
                cpu: 1.0
              limits:
                memory: 512M
                cpu: 1.0
