apiVersion: apps/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: containerdeploymentunit-mongo # Should generate a uniq name
spec:
  replicas: 1
  template:
    metadata:
      labels:
        anti_affinity_label: containerdeploymentunit-mongo
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: anti_affinity_label
                  operator: In
                  values:
                  - containerdeploymentunit_mongo_2
              topologyKey: kubernetes.io/hostname
      containers:
        - name: mongo
          image: mongo:latest
          resources:
            requests:
              memory: 512M
              cpu: 1.0
            limits:
              memory: 512M
              cpu: 1.0
          ports:
          - containerPort: 27017
