apiVersion: v1
kind: Service
metadata:
  name: Mongo_Service # Should generate a uniq name
spec:
  ports:
    - name: Mongo_docker_endpoint
      port: { get_property: [Mongo, docker_endpoint, port] }
  selector:
    app: ContainerDeploymentUnit_Mongo # podname
  type: NodePort