apiVersion: apps/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ContainerDeploymentUnit # Should generate a uniq name
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: Nodecellar # Should generate a uniq name
        env:
          LOG_LEVEL: "DEBUG"
          MONGO_HOST: localhost
          MONGO_PORT: 27017
          NODECELLAR_PORT: 3000
        image: afraisse/nodecellar:exp
        resources:
          requests:
            memory: 1024M
            cpu: 1.0
          limits:
            memory: 1024M
            cpu: 1.0
        command: ["/bin/bash", "-c", "cd /nodecellar && nodejs server.js" ]
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /tmp/var
          name: DockerExtVolume
      - name: Mongo
        image: mongo:latest
        resources:
          requests:
            memory: 512M
            cpu: 1.0
          limits:
            memory: 512M
            cpu: 1.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /tmp/var
          name: DockerExtVolume
      volumes:
      - name: DockerExtVolume
        path: /mnt/host_volume_path